[package]
name = "quick-carbon"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
clipboard-win = "5.4.0"
enigo = "0.3.0"
open = "5.3.1"
urlencoding = "2.1.3"
